package controlador;
// Generated Apr 8, 2019 3:27:52 PM by Hibernate Tools 4.3.1



/**
 * Califica generated by hbm2java
 */
public class Califica  implements java.io.Serializable {


     private CalificaId id;

    public Califica() {
    }

    public Califica(CalificaId id) {
       this.id = id;
    }
   
    public CalificaId getId() {
        return this.id;
    }
    
    public void setId(CalificaId id) {
        this.id = id;
    }




}


